
<?php
 // module/Album/view/album/album/add.phtml:

 $title = 'صفحة سؤال';
 $this->headTitle($title);
 ?>
    
<div class="page-header">
 <h1><?php echo $this->escapeHtml($title); ?></h1></div> 
<div class="right">
 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url('questions', array('action' => 'view','id'     => $this->id,)));
 $form->prepare();
$questionAnswers = array();
$question = '' ;
foreach($data['question'] as $row){
    $question = $row->question;
    $title = $row->title;
     $questionAnswers[$row->answerid] = array('title' => $row->title,'question' => $row->question,'answer'=>$row->answer,'correct'=>$row->correct,'answeredid'=>$row->answeredid,'answeredusername'=>$row->answeredusername);
 }
 

 

 echo $this->form()->openTag($form);
 

 ?>
    <h4>السؤال الختصر</h4>
    <div class="row" > 
            <div class="col-sm-12">
    <?php
 echo "<h1>$title</h1>";
 ?>
        </div>
            </div>
    <h4>السؤال التفصيلي</h4>
        <div class="row" > 
            <div class="col-sm-12">
    <?php
 echo "<h3>$question</h3>";
 ?>
        </div>
            </div>
    <h4>الأجوبة</h4>
    <?php
    foreach($questionAnswers as $key => $row){
        ?>
    <div class="row">
        <div class="col-sm-11">
    <?php
 echo "<h4>".$row['answer']."</h4> ";
 $answerId = $key;
 ?>
        </div>
        <div class="col-sm-1">
            <?php
 if($row['correct']){
     
     echo "<div class = 'correct-arrow allanswer' id = '$answerId'><h1>&#10004;</h1></div>";
 }
 else{
     echo "<div class = 'unanswered-arrow allanswer' id = '$answerId'><h1>&#10004;</h1></div>";
 }
 
 
 ?>
        </div>
        <?php
    }
        ?>
        
        </div>
    
    <div class="form-group">
        
    <?php
 echo $this->formRow($form->get('answer'));
 ?>
         
        </div>
    
    
        <?php
 echo $this->formSubmit($form->get('submit')->setValue('أضف جواب'));
 echo $this->form()->closeTag();
 ?>
</div>
<script>
$(document).ready(function(){
    $('.allanswer').click(function(){
        
         var oldCorrect = $('.correct-arrow').attr('id');
         $('#'+oldCorrect).removeClass('correct-arrow');
         $('#'+oldCorrect).addClass('unanswered-arrow');
        $(this).removeClass('unanswered-arrow'); 
        $(this).addClass('correct-arrow');
         
                    var id = $(this).attr('id');
                    $.ajax({
                        url: '<?php echo $this->basePath()?>/questions/markCorrect',
                        method: 'POST',
                        data: {
                            id: id},
                        success: function () {
                           
                        }
                    });
               
    });
});
</script>