<?php echo $this->doctype(); ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('ZF2 ' . $this->translate('قرية العرب'))->setSeparator(' - ')->setAutoEscape(false) ?>

        <?php echo $this->headMeta()->appendName('viewport', 'width=device-width, initial-scale=1.0') ?>

        <!-- Le styles -->
        <?php
        echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/images/favicon.ico'))
                //->prependStylesheet($this->basePath() . '/css/StickyNotes.css')
                ->prependStylesheet($this->basePath() . '/css/main.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap-responsive.min.css')
                ->prependStylesheet($this->basePath() . '/css/style.css')
                ->prependStylesheet($this->basePath() . '/css/bootstrap.min.css')
        ?>

        <!-- Scripts -->
        <?php
        echo $this->headScript()->prependFile($this->basePath() . '/js/html5.js', 'text/javascript', array('conditional' => 'lt IE 9',))
                ->prependFile($this->basePath() . '/js/bootstrap.min.js')
                ->prependFile($this->basePath() . '/js/jquery.min.js')
                ->appendFile($this->basePath() . '/js/custom.js')
                ->appendFile($this->basePath() . '/tinymce/js/tinymce/tinymce.min.js')
        ?>
  <script>tinymce.init({ selector:'textarea' });</script>
    </head>
    <body>
        
        <nav id="myNavbar" class="navbar navbar-default navbar-inverse navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="<?php echo $this->url('home') ?>">قرية العرب</a>
        </div>
        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="nav navbar-nav">
                <!-- http://www.tutorialrepublic.com -->
                <li class="active"><a href="<?php echo $this->basePath(); ?>" target="">Home</a></li>
                <li><a href="" target="">About</a></li>
                <li><a href="" target="">Contact</a></li>
                <?php
               $userID = $this->identity();
                if(!isset($userID)){
                    ?>
                <li><a href="<?php echo $this->basePath(); ?>/user/login" target="">Login</a></li>
                <?php
                }else{
                    ?>
                <li><a href="<?php echo $this->basePath(); ?>/user/logout" target="">Logout</a></li>
                <?php
                }
                ?>
            </ul>
        </div>
    </div>
            </nav>
        
        
        <div id="wrapper">
    <div id="sidebar-wrapper">
        <ul class="sidebar-nav">
            <li class="sidebar-brand"><a href="#"></a></li>
            <li><a href="#"></a></li>
            <li><a href="#"></a></li>
            <li><a href="#"></a></li>
        </ul>
        أهلاً وسهلاً بكم في موقع قرية العرب
    </div>
            <div id="page-content-wrapper">
        <div class="page-content">
            <div class="container">
                <div class="row">
                    <div class="col-md-10">
                        <?php echo $this->content; ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
        
        <div class="container">
            

            <hr>
            <footer>
                
            </footer>
        </div> <!-- /container -->
<?php echo $this->inlineScript() ?>
    </body>
</html>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-48292514-4', 'auto');
  ga('send', 'pageview');

</script>